### ISSUE TITLE
Is there a way to tune transfer speed?

### ISSUE THREAD

**Issue by hwshadow** [JamesDunne/lancaster-go#1]
First of all cool project!  Thanks for contributing it.  

I have dowmloaded and compiled it for windows and noticed I was getting just 10MiB/s on both LAN and loopback tests.   Running iperf3 i see an average sustained speed on the loopback of about 5.3GiB/s using UDP. 

Is there 
a) any configuration within lancaster you suggest I review?
b) can you suggest any system configurations to look at?
c) any limitation imposed upon lancaster to rate limit to the 10MiB/s I am observing?

Loopback MTU is 4294967295 
LAN MTU is 1500

Thanks in advance for any attention you might give this.  Best Regards~

**Comment by JamesDunne** [comment]
Hey, thanks for the interest and the comment! Last time I touched this was probably 4 years ago and I remember struggling a bit to get it stable let alone performant. The protocol is a rather simple NAK-based protocol where the client just sends a list of packets it has not received yet and the server continually tries to satisfy those NAKed packets to all clients. There appear to be some hard-coded timing constants and retry counters buried in the code which is limiting performance to 10MiB/s. Seems this needs a little bit of a reimplementation to make it more reliable first. Sorry about that; I usually do this with most projects and just leave them out there lol, no guarantees.

**Comment by hwshadow** [comment]
No worries i saw it wasn't an active project, but noticed you were active so I just thought I'd ask to gather insight.  Thanks for the information I will play around with it ;)  have a great rest of your day :)
